### ISSUE TITLE
Use metabase

### ISSUE THREAD

**Issue by VolkerSchiewe** [VolkerSchiewe/trumpet#2]
### TODO
- [x] Run metabase on heroku
- [ ] sync firestore with bigquery
- [ ] connect metabase and bigquery
